version: '3'

services:
  app:
    build: ./app
    container_name: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: surveys
      MYSQL_USER: www-data
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql